<Project>
  <Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Packages.props', '$(MSBuildThisFileDirectory)../'))" />
  <ItemGroup Label="Common packages">
    <PackageVersion Include="DotNet.ReproducibleBuilds" Version="2.0.5" PrivateAssets="all" IncludeAssets="$(IncludedAssets)" />
  </ItemGroup>
  <ItemGroup Label="Application packages">
    <PackageVersion Include="Microsoft.Extensions.Localization.Abstractions" Version="11.0.100-preview.6.26359.118" />
  </ItemGroup>
  <ItemGroup Label="Infrastructure packages">
    <PackageVersion Include="Microsoft.Extensions.Caching.Memory" Version="11.0.100-preview.6.26359.118" />
    <PackageVersion Include="Microsoft.Extensions.Http" Version="11.0.100-preview.6.26359.118" />
  </ItemGroup>
  <ItemGroup Label="Web packages">
    <PackageVersion Include="Markdig" Version="1.3.2" />
    <PackageVersion Include="Microsoft.AspNetCore.Components.WebAssembly" Version="11.0.100-preview.6.26359.118" />
    <PackageVersion Include="Microsoft.AspNetCore.Components.Gateway" Version="11.0.100-preview.6.26359.118" PrivateAssets="all" IncludeAssets="$(IncludedAssets)" />
    <PackageVersion Include="Microsoft.Extensions.Localization" Version="11.0.100-preview.6.26359.118" />
    <PackageVersion Include="Microsoft.TypeScript.MSBuild" Version="7.0.0" PrivateAssets="all" IncludeAssets="$(IncludedAssets)" />
  </ItemGroup>
</Project>
