name: Prometheus

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * 2'

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    name: Update countries data
    runs-on: windows-latest
    env:
      prometheus: ./src/Prometheus/Prometheus.csproj

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x
          dotnet-quality: preview

      - name: Restore dependencies
        run: dotnet restore ${{ env.prometheus }}

      - name: Publish
        run: dotnet publish ${{ env.prometheus }} --output ./artifacts

      - name: Run Prometheus
        run: ./artifacts/Prometheus.exe

      - name: Create pull request
        uses: peter-evans/create-pull-request@v7
        with:
          title: "Update countries.json"
          base: main
          branch: update-countries-json
          commit-message: "Update countries.json"
          body: This PR updates the countries json files with the latest data.
          labels: dependencies, prometheus
          reviewers: beauchama
          assignees: beauchama
          token: ${{ secrets.GITHUB_TOKEN }}
