name: Prometheus

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * 2'

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    name: Update countries data
    runs-on: windows-latest
    env:
      prometheus: ./src/Prometheus/Prometheus.csproj

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x
          dotnet-quality: preview

      - name: Restore dependencies
        run: dotnet restore ${{ env.prometheus }}

      - name: Publish
        run: dotnet publish ${{ env.prometheus }} --output .

      - name: Run Prometheus
        run: ./Prometheus.exe

      - name: Detect changes
        run: |
          git config --global core.autocrlf false
          if (git diff --quiet)
          {
            echo "No changes detected."
            echo "changed=false" >> $env:GITHUB_ENV
          }
          else
          {
            echo "Changes detected."
            echo "changed=true" >> $env:GITHUB_ENV
            exit 0
          }

      - name: Commit changes
        if: ${{ env.changed }} == 'true'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          branch="update-countries-json"
          git checkout -b $branch
          git add .
          git commit -m "Update countries.json"
          git push -u origin $branch
          echo "branch=$branch" >> $env:GITHUB_ENV

      - name: Create pull request
        if: ${{ env.changed }} == 'true'
        uses: peter-evans/create-pull-request@v7
        with:
          title: "Update countries.json"
          base: main
          branch: ${{ env.branch }}
          commit-message: "Update countries.json"
          body: This PR updates the countries json files with the latest data.
          labels: dependencies, prometheus
          reviewers: beauchama
          assignees: beauchama
          token: ${{ secrets.GITHUB_TOKEN }}
