name: Pull Request

on:
  pull_request:
    branches: [main]

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  build:
    name: Build/Unit Test
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x
          dotnet-quality: preview

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration release --no-restore

      - name: Test
        run: dotnet test --configuration release --no-build -- --report-trx

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: '**/TestResults/*.trx'

  publish:
    name: Publish test results
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download test results
        uses: actions/download-artifact@v4
        with:
          name: test-results

      - name: Publish test results
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: '**/*.trx'
