name: Pull Request

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
    paths: [ 'src/**', 'tests/**', .github/workflows/pull-request.yml ]

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  build:
    name: Build/Unit Test
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x
          dotnet-quality: preview

      - name: Install wasm-tools workload
        run: dotnet workload install wasm-tools

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration release --no-restore

      - name: Test
        continue-on-error: true
        run: dotnet test --project .\tests\Unit.Tests\Unit.Tests.csproj --configuration release --no-build --report-trx

      - name: Publish test results
        if: (!cancelled())
        uses: EnricoMi/publish-unit-test-result-action/windows@v2
        with:
          files: '**/TestResults/*.trx'
