name: Staging

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  staging:
    name: Staging environment

    permissions:
      contents: read
      deployments: write

    uses: kappaduck/atlas/.github/workflows/build.yml@feature/deploy-staging
    with:
      environment: staging
    secrets: inherit
